/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        ConteudojPanel = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAutores = new javax.swing.JMenuItem();
        MenuCadastros = new javax.swing.JMenuItem();
        MenuEditoras = new javax.swing.JMenuItem();
        MenuEmprestimos = new javax.swing.JMenuItem();
        MenuFuncionarios = new javax.swing.JMenuItem();
        MenuLivros = new javax.swing.JMenuItem();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        ConteudojPanel.setLayout(new javax.swing.BoxLayout(ConteudojPanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(ConteudojPanel);

        jMenu1.setText("File");

        MenuAutores.setText("Autores");
        MenuAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAutoresActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAutores);

        MenuCadastros.setText("Cadastros");
        MenuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastros);

        MenuEditoras.setText("Editoras");
        MenuEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditorasActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEditoras);

        MenuEmprestimos.setText("Empréstimos");
        MenuEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmprestimosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuEmprestimos);

        MenuFuncionarios.setText("Funcionários");
        MenuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFuncionarios);

        MenuLivros.setText("Livros");
        MenuLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLivros);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAutoresActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new AutoresjPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuAutoresActionPerformed

    private void MenuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrosActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new CadastrojPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuCadastrosActionPerformed

    private void MenuEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmprestimosActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new EmprestimojPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuEmprestimosActionPerformed

    private void MenuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionariosActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new FuncionariojPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuFuncionariosActionPerformed

    private void MenuLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLivrosActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new LivrojPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuLivrosActionPerformed

    private void MenuEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditorasActionPerformed
        ConteudojPanel.removeAll();
        ConteudojPanel.add(new EditorajPanel());
        ConteudojPanel.setVisible(false);
        ConteudojPanel.setVisible(true);
    }//GEN-LAST:event_MenuEditorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConteudojPanel;
    private javax.swing.JMenuItem MenuAutores;
    private javax.swing.JMenuItem MenuCadastros;
    private javax.swing.JMenuItem MenuEditoras;
    private javax.swing.JMenuItem MenuEmprestimos;
    private javax.swing.JMenuItem MenuFuncionarios;
    private javax.swing.JMenuItem MenuLivros;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
